### ISSUE TITLE
[Issue] Gateway disappears from explorer.nymtech.net rules after a while

### ISSUE THREAD

**Issue by ststefa** [nymtech/docs#300]
**Describe the issue**
After bonding my gateway with wallet 1.0.8 (which uses the wrong default WS port 1790 by default), the gateway initially showed up in explorer. After a while it vanished again. I _guess_ that this is due to the explorer service not being able to contact my gateway on the 1790 port and kicking it out. It would be nice to have some insight into (or docs about) these flows and rules.

I had a similar case trying to advertise my gateway with a DNS name instead on an IP. The symptoms were similar (appeared on explorer, then vanished after a while) and again I can only guess that it must be related to some kind of failing validation by unknown rules. I attempted that several times and eventually gave up on it.

**Expected behaviour**
For debugging/troubleshooting and to improve general understanding it would be nice to have a deeper insight (like docs+tools) into the rules and flows by which central services (like the explorer) behave. Otherwise it's just guesswork which leads to avoidable maintenance/support effort.

**Comment by tommyv1987** [comment]
@mfahampshire, can i get your thoughts on this one please?

**Comment by mfahampshire** [comment]
Thanks for raising this @ststefa . 

>  I guess that this is due to the explorer service not being able to contact my gateway on the 1790 port and kicking it out.

Since ports can be configured by the user, if you bonded this gateway with this port, it should be saved in the smart contract, which is what the explorer should be checking, so I'd be surprised if it was this. 

> I had a similar case trying to advertise my gateway with a DNS name instead on an IP....and again I can only guess that it must be related to some kind of failing validation by unknown rules

I'd be surprised if that was true also, but I will have to check into it. 

Your suggestions are good - I will keep this issue open for the moment to refer to in the ticket I make for adding debug information to the docs
